version: '3.8'

services:
  whois-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: whois-query-tool:latest
    container_name: whois-query-tool
    restart: unless-stopped
    
    # 端口映射
    ports:
      - "3000:3000"
    
    # 环境变量
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      # 可根据需要添加其他环境变量
      # - CUSTOM_API_KEY=your_api_key
      # - CACHE_TTL=3600
    
    # 数据卷挂载（可选）
    volumes:
      # 挂载日志目录（如果需要持久化日志）
      - ./logs:/app/logs
      # 挂载配置文件（如果有自定义配置）
      # - ./config:/app/config:ro
    
    # 健康检查
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # 网络配置
    networks:
      - whois-network

# 网络定义
networks:
  whois-network:
    driver: bridge
    name: whois-network

# 数据卷定义（可选）
volumes:
  whois-logs:
    driver: local
    name: whois-logs