version: '3.8'

services:
  whois-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    image: whois-query-tool:dev
    container_name: whois-query-tool-dev
    restart: unless-stopped
    
    # 端口映射
    ports:
      - "3000:3000"
      - "9229:9229"  # Node.js 调试端口
    
    # 环境变量
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true  # 支持文件监听
    
    # 数据卷挂载（开发模式）
    volumes:
      # 挂载源代码目录，支持热重载
      - .:/app
      - /app/node_modules
      - /app/.next
      # 挂载日志目录
      - ./logs:/app/logs
    
    # 工作目录
    working_dir: /app
    
    # 启动命令（开发模式）
    command: npm run dev
    
    # 网络配置
    networks:
      - whois-dev-network
    
    # 依赖服务（如果需要数据库等）
    # depends_on:
    #   - redis
    #   - postgres

# 开发环境网络
networks:
  whois-dev-network:
    driver: bridge
    name: whois-dev-network

# 可选：添加开发环境依赖服务
# services:
#   redis:
#     image: redis:7-alpine
#     container_name: whois-redis-dev
#     ports:
#       - "6379:6379"
#     networks:
#       - whois-dev-network